layout_spectrum: 0.3284698
typography_spectrum: 0.6795617
color:
  saturation: 0.6706882
  lightness: 0.581
  brandStrength: 0.9698797
  rhythmicContrast: 0.007332323
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: My precious
